### ISSUE TITLE
Dependencies not loading when bundle install is executed

### ISSUE THREAD

**Issue by angulargirl** [scottmuc/yari#24]
The bundle install command however starts complaining that it can't find gems to install. After some detective work, I can see that the Gemfile under Octopress is adding gems as i install them manually one by one. For more details perhaps someone can answer: http://stackoverflow.com/questions/22382173/installing-octopress-on-windows-7-using-yari-dependencies-not-loading-when-bundl--Much appreciated

**Comment by scottmuc** [comment]
Closing as I see this was resolved in the StackOverflow post.
